# Generated by Django 4.0.2 on 2022-02-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='PhotoFIleName',
            new_name='PhotoName',
        ),
    ]
