# Generated by Django 4.0.2 on 2022-02-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_rename_photofilename_employees_photoname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employees'},
        ),
    ]
